export function definePresets() {
    return {
        V: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 50, max: 300 },
                SmallCircle: { min: 1, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 9 },
                StartCP: { value: 20 },
                MiddleCP: { value: 49 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 21 },
                StartCP: { value: 19 },
                MiddleCP: { value: 32 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 32 },
                StartCP: { value: 16 },
                MiddleCP: { value: 27 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 47 },
                StartCP: { value: 14 },
                MiddleCP: { value: 21 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 39 },
                StartCP: { value: 13 },
                MiddleCP: { value: 18 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 49 },
                StartCP: { value: 11 },
                MiddleCP: { value: 15 },
                Segments: { value: 33, max: 33 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 55 },
                StartCP: { value: 10 },
                MiddleCP: { value: 17 },
                Segments: { value: 37, max: 37 },
            },
        },
        V2: {
            sliders: [
                { name: 'Knots' },
                { name: 'ExtraCircle' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'CP1' },
                { name: 'CP2' },
                { name: 'Tilt' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                ExtraCircle: { min: 50, max: 500 },
                LargeCircle: { min: 50, max: 400 },
                SmallCircle: { min: 1, max: 200 },
                ExtraCP: { min: 0, max: 70 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                ExtraAngle: { min: -180, max: 180 },
                CP1: { min: 0, max: 80 },
                CP2: { min: 0, max: 80 },
                Tilt: { min: -180, max: 180 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 60 },
                ExtraCP: { value: 46 },
                StartCP: { value: 45 },
                MiddleCP: { value: 19 },
                ExtraAngle: { value: 0 },
                CP1: { value: 32 },
                CP2: { value: 39 },
                Tilt: { value: -23 },
                Segments: { value: 19, max: 19 },
            },
            4: {
                Knots: { value: 4 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 88 },
                ExtraCP: { value: 42 },
                StartCP: { value: 37 },
                MiddleCP: { value: 19 },
                ExtraAngle: { value: 0 },
                CP1: { value: 22 },
                CP2: { value: 27 },
                Tilt: { value: -29 },
                Segments: { value: 25, max: 25 },
            },
            4.1: {
                Knots: { value: 4 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 88 },
                ExtraCP: { value: 25 },
                StartCP: { value: 25 },
                MiddleCP: { value: 35 },
                ExtraAngle: { value: 0 },
                CP1: { value: 46 },
                CP2: { value: 43 },
                Tilt: { value: 158 },
                Segments: { value: 25, max: 25 },
            },
            5: {
                Knots: { value: 5 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 122 },
                ExtraCP: { value: 37 },
                StartCP: { value: 37 },
                MiddleCP: { value: 16 },
                ExtraAngle: { value: 0 },
                CP1: { value: 26 },
                CP2: { value: 29 },
                Tilt: { value: -33 },
                Segments: { value: 31, max: 31 },
            },
            6: {
                Knots: { value: 6 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 124 },
                ExtraCP: { value: 37 },
                StartCP: { value: 29 },
                MiddleCP: { value: 12 },
                ExtraAngle: { value: 0 },
                CP1: { value: 24 },
                CP2: { value: 30 },
                Tilt: { value: -21 },
                Segments: { value: 37, max: 37 },
            },
            7: {
                Knots: { value: 7 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 162 },
                ExtraCP: { value: 37 },
                StartCP: { value: 29 },
                MiddleCP: { value: 12 },
                ExtraAngle: { value: 0 },
                CP1: { value: 24 },
                CP2: { value: 30 },
                Tilt: { value: -21 },
                Segments: { value: 43, max: 43 },
            },
            8: {
                Knots: { value: 8 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 167 },
                ExtraCP: { value: 37 },
                StartCP: { value: 22 },
                MiddleCP: { value: 10 },
                ExtraAngle: { value: 0 },
                CP1: { value: 20 },
                CP2: { value: 29 },
                Tilt: { value: -20 },
                Segments: { value: 49, max: 49 },
            },
            9: {
                Knots: { value: 9 },
                ExtraCircle: { value: 336 },
                LargeCircle: { value: 291 },
                SmallCircle: { value: 169 },
                ExtraCP: { value: 37 },
                StartCP: { value: 22 },
                MiddleCP: { value: 8 },
                ExtraAngle: { value: 0 },
                CP1: { value: 20 },
                CP2: { value: 29 },
                Tilt: { value: -20 },
                Segments: { value: 55, max: 55 },
            },
        },
        V3: {
            sliders: [
                { name: 'Knots' },
                { name: 'ExtraCircle' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'CP1' },
                { name: 'CP2' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                ExtraCircle: { min: 50, max: 500 },
                LargeCircle: { min: 50, max: 400 },
                SmallCircle: { min: 1, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                CP1: { min: 0, max: 80 },
                CP2: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots:       { value: 3           },
                ExtraCircle: { value: 80          },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 15          },
                StartCP:     { value: 40          },
                MiddleCP:    { value: 60          },
                CP1:         { value: 52          },
                CP2:         { value: 62          },
                Segments:    { value: 13, max: 13 },
            },
            4: {
                Knots:       { value: 4           },
                ExtraCircle: { value: 100         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 30          },
                StartCP:     { value: 38          },
                MiddleCP:    { value: 40          },
                CP1:         { value: 52          },
                CP2:         { value: 62          },
                Segments:    { value: 17, max: 17 },
            },
            5: {
                Knots:       { value: 5           },
                ExtraCircle: { value: 120         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 45          },
                StartCP:     { value: 36          },
                MiddleCP:    { value: 30          },
                CP1:         { value: 52          },
                CP2:         { value: 62          },
                Segments:    { value: 21, max: 21 },
            },
            6: {
                Knots:       { value: 6           },
                ExtraCircle: { value: 140         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 60          },
                StartCP:     { value: 34          },
                MiddleCP:    { value: 27          },
                CP1:         { value: 52          },
                CP2:         { value: 62          },
                Segments:    { value: 25, max: 25 },
            },
            7: {
                Knots:       { value: 7           },
                ExtraCircle: { value: 160         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 75          },
                StartCP:     { value: 32          },
                MiddleCP:    { value: 24          },
                CP1:         { value: 52          },
                CP2:         { value: 62          },
                Segments:    { value: 29, max: 29 },
            },
            8: {
                Knots:       { value: 8           },
                ExtraCircle: { value: 150         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 90          },
                StartCP:     { value: 30          },
                MiddleCP:    { value: 20          },
                CP1:         { value: 52          },
                CP2:         { value: 52          },
                Segments:    { value: 33, max: 33 },
            },
            9: {
                Knots:       { value: 9           },
                ExtraCircle: { value: 200         },
                LargeCircle: { value: 351         },
                SmallCircle: { value: 115         },
                StartCP:     { value: 28          },
                MiddleCP:    { value: 20          },
                CP1:         { value: 52          },
                CP2:         { value: 42          },
                Segments:    { value: 37, max: 37 },
            },
        },
        W: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 50, max: 300 },
                SmallCircle: { min: 1, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 62 },
                SmallCircle: { value: 28 },
                StartCP: { value: 23 },
                MiddleCP: { value: 20 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 100 },
                SmallCircle: { value: 47 },
                StartCP: { value: 23 },
                MiddleCP: { value: 16 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 122 },
                SmallCircle: { value: 37 },
                StartCP: { value: 21 },
                MiddleCP: { value: 14 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 138 },
                SmallCircle: { value: 53 },
                StartCP: { value: 21 },
                MiddleCP: { value: 12 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 136 },
                SmallCircle: { value: 27 },
                StartCP: { value: 17 },
                MiddleCP: { value: 11 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 158 },
                SmallCircle: { value: 60 },
                StartCP: { value: 19 },
                MiddleCP: { value: 9 },
                Segments: { value: 33, max: 33 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 177 },
                SmallCircle: { value: 42 },
                StartCP: { value: 17 },
                MiddleCP: { value: 9 },
                Segments: { value: 37, max: 37 },
            },
        },
        W2: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 50, max: 300 },
                SmallCircle: { min: 1, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 181 },
                SmallCircle: { value: 26 },
                StartCP: { value: 27 },
                MiddleCP: { value: 13 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 137 },
                SmallCircle: { value: 32 },
                StartCP: { value: 24 },
                MiddleCP: { value: 15 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 129 },
                SmallCircle: { value: 46 },
                StartCP: { value: 28 },
                MiddleCP: { value: 17 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 112 },
                SmallCircle: { value: 64 },
                StartCP: { value: 26 },
                MiddleCP: { value: 20 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 79 },
                SmallCircle: { value: 44 },
                StartCP: { value: 24 },
                MiddleCP: { value: 19 },
                Segments: { value: 29, max: 29 },
            },
        },
        Ra: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'ExtraCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'ExtraCP' },
                { name: 'Tilt' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 12 },
                LargeCircle: { min: 50, max: 1000 },
                SmallCircle: { min: 1, max: 500 },
                ExtraCircle: { min: -100, max: 800 },
                StartCP: { min: 0, max: 250 },
                MiddleCP: { min: 0, max: 160 },
                ExtraCP: { min: 0, max: 160 },
                Tilt: { min: -220, max: 220 },
                Segments: { min: 2, max: 73 },
            },
            3.1: {
                Knots: { value: 3 },
                LargeCircle: { value: 500 },
                SmallCircle: { value: 171 },
                ExtraCircle: { value: 245 },
                StartCP: { value: 71 },
                MiddleCP: { value: 43 },
                ExtraCP: { value: 24 },
                Tilt: { value: -62 },
                Segments: { value: 19, max: 19 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 566, max: 2000 },
                SmallCircle: { value: 139, max: 1000 },
                ExtraCircle: { value: 257 },
                StartCP: { value: 84, max: 500 },
                MiddleCP: { value: 33 },
                ExtraCP: { value: 30 },
                Tilt: { value: -62 },
                Segments: { value: 19, max: 19 },
            },
            4.1: {
                Knots: { value: 4 },
                LargeCircle: { value: 646 },
                SmallCircle: { value: 141 },
                ExtraCircle: { value: 345 },
                StartCP: { value: 55 },
                MiddleCP: { value: 44 },
                ExtraCP: { value: 55 },
                Tilt: { value: -47 },
                Segments: { value: 25, max: 25 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 920 },
                SmallCircle: { value: 209 },
                ExtraCircle: { value: 496 },
                StartCP: { value: 134 },
                MiddleCP: { value: 53 },
                ExtraCP: { value: 82 },
                Tilt: { value: -4 },
                Segments: { value: 25, max: 25 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 707 },
                SmallCircle: { value: 111 },
                ExtraCircle: { value: 363 },
                StartCP: { value: 79 },
                MiddleCP: { value: 30 },
                ExtraCP: { value: 51 },
                Tilt: { value: 1 },
                Segments: { value: 31, max: 31 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 671 },
                SmallCircle: { value: 181 },
                ExtraCircle: { value: 419 },
                StartCP: { value: 56 },
                MiddleCP: { value: 32 },
                ExtraCP: { value: 56 },
                Tilt: { value: 4 },
                Segments: { value: 37, max: 37 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 691 },
                SmallCircle: { value: 187 },
                ExtraCircle: { value: 450 },
                StartCP: { value: 51 },
                MiddleCP: { value: 30 },
                ExtraCP: { value: 51 },
                Tilt: { value: 5 },
                Segments: { value: 43, max: 43 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 718 },
                SmallCircle: { value: 225 },
                ExtraCircle: { value: 450 },
                StartCP: { value: 44 },
                MiddleCP: { value: 34 },
                ExtraCP: { value: 44 },
                Tilt: { value: 4 },
                Segments: { value: 49, max: 49 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 782 },
                SmallCircle: { value: 237 },
                ExtraCircle: { value: 530 },
                StartCP: { value: 47 },
                MiddleCP: { value: 26 },
                ExtraCP: { value: 47 },
                Tilt: { value: 3 },
                Segments: { value: 55, max: 55 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 782 },
                SmallCircle: { value: 245 },
                ExtraCircle: { value: 572 },
                StartCP: { value: 41 },
                MiddleCP: { value: 20 },
                ExtraCP: { value: 41 },
                Tilt: { value: 0 },
                Segments: { value: 61, max: 61 },
            },
            11: {
                Knots: { value: 11 },
                LargeCircle: { value: 781 },
                SmallCircle: { value: 268 },
                ExtraCircle: { value: 624 },
                StartCP: { value: 43 },
                MiddleCP: { value: 15 },
                ExtraCP: { value: 43 },
                Tilt: { value: 3 },
                Segments: { value: 67, max: 67 },
            },
            12: {
                Knots: { value: 12 },
                LargeCircle: { value: 721 },
                SmallCircle: { value: 274 },
                ExtraCircle: { value: 585 },
                StartCP: { value: 37 },
                MiddleCP: { value: 13 },
                ExtraCP: { value: 37 },
                Tilt: { value: 3 },
                Segments: { value: 73, max: 73 },
            },
        },
        S: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 3 },
                LargeCircle: { min: 50, max: 300 },
                SmallCircle: { min: 1, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 75 },
                SmallCircle: { value: 12 },
                StartCP: { value: 24 },
                MiddleCP: { value: 15 },
                Segments: { value: 25, max: 25 },
            },
        },
        Pe: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 135 },
                SmallCircle: { value: 60 },
                StartCP: { value: 50 },
                MiddleCP: { value: 33 },
                Segments: { value: 7, max: 7 },
            },
            3.1: {
                Knots: { value: 3 },
                LargeCircle: { value: 173 },
                SmallCircle: { value: 50 },
                StartCP: { value: 36 },
                MiddleCP: { value: 60 },
                Segments: { value: 7, max: 7 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 188 },
                SmallCircle: { value: 99 },
                StartCP: { value: 70 },
                MiddleCP: { value: 55 },
                Segments: { value: 9, max: 9 },
            },
            4.1: {
                Knots: { value: 4 },
                LargeCircle: { value: 245 },
                SmallCircle: { value: 95 },
                StartCP: { value: 35 },
                MiddleCP: { value: 69 },
                Segments: { value: 9, max: 9 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 169 },
                SmallCircle: { value: 43 },
                StartCP: { value: 45 },
                MiddleCP: { value: 65 },
                Segments: { value: 11, max: 11 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 169 },
                SmallCircle: { value: 43 },
                StartCP: { value: 24 },
                MiddleCP: { value: 65 },
                Segments: { value: 13, max: 13 },
            },
            6.1: {
                Knots: { value: 6 },
                LargeCircle: { value: 185 },
                SmallCircle: { value: 77 },
                StartCP: { value: 40 },
                MiddleCP: { value: 68 },
                Segments: { value: 13, max: 13 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 251 },
                SmallCircle: { value: 52 },
                StartCP: { value: 26 },
                MiddleCP: { value: 67 },
                Segments: { value: 15, max: 15 },
            },
        },
        Pi: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 173 },
                SmallCircle: { value: 50 },
                StartCP: { value: 36 },
                MiddleCP: { value: 60 },
                Segments: { value: 7, max: 7 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 100 },
                StartCP: { value: 36 },
                MiddleCP: { value: 55 },
                Segments: { value: 11, max: 11 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 149 },
                SmallCircle: { value: 115 },
                StartCP: { value: 23 },
                MiddleCP: { value: 16 },
                Segments: { value: 15, max: 15 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 188 },
                SmallCircle: { value: 157 },
                StartCP: { value: 26 },
                MiddleCP: { value: 18 },
                Segments: { value: 19, max: 19 },
            },
        },
        R: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 100 },
                StartCP: { value: 14 },
                MiddleCP: { value: 10 },
                Segments: { value: 7, max: 7 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 214 },
                SmallCircle: { value: 94 },
                StartCP: { value: 36 },
                MiddleCP: { value: 55 },
                Segments: { value: 9, max: 9 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 100 },
                StartCP: { value: 36 },
                MiddleCP: { value: 55 },
                Segments: { value: 11, max: 11 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 173 },
                SmallCircle: { value: 79 },
                StartCP: { value: 20 },
                MiddleCP: { value: 26 },
                Segments: { value: 13, max: 13 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 155 },
                StartCP: { value: 52 },
                MiddleCP: { value: 40 },
                Segments: { value: 15, max: 15 },
            },
            7.1: {
                Knots: { value: 7 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 100 },
                StartCP: { value: 52 },
                MiddleCP: { value: 40 },
                Segments: { value: 15, max: 15 },
            },
            7.2: {
                Knots: { value: 7 },
                LargeCircle: { value: 211 },
                SmallCircle: { value: 155 },
                StartCP: { value: 52 },
                MiddleCP: { value: 40 },
                Segments: { value: 15, max: 15 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 192 },
                SmallCircle: { value: 96 },
                StartCP: { value: 7 },
                MiddleCP: { value: 46 },
                Segments: { value: 17, max: 17 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 208 },
                SmallCircle: { value: 87 },
                StartCP: { value: 8 },
                MiddleCP: { value: 45 },
                Segments: { value: 19, max: 19 },
            },
        },
        Y: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 175 },
                SmallCircle: { value: 50 },
                StartCP: { value: 10 },
                MiddleCP: { value: 23 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 50 },
                StartCP: { value: 10 },
                MiddleCP: { value: 26 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 50 },
                StartCP: { value: 10 },
                MiddleCP: { value: 26 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 75 },
                StartCP: { value: 10 },
                MiddleCP: { value: 26 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 222 },
                SmallCircle: { value: 75 },
                StartCP: { value: 8 },
                MiddleCP: { value: 27 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 261 },
                SmallCircle: { value: 76 },
                StartCP: { value: 7 },
                MiddleCP: { value: 31 },
                Segments: { value: 33, max: 33 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 261 },
                SmallCircle: { value: 87 },
                StartCP: { value: 7 },
                MiddleCP: { value: 31 },
                Segments: { value: 37, max: 37 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 261 },
                SmallCircle: { value: 99 },
                StartCP: { value: 7 },
                MiddleCP: { value: 31 },
                Segments: { value: 41, max: 41 },
            },
        },
        YPlus: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Tilt' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Tilt: { min: -150, max: 150 },
                Segments: { min: 2, max: 25 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 227 },
                SmallCircle: { value: 29 },
                StartCP: { value: 16 },
                MiddleCP: { value: 30 },
                Tilt: { value: -6 },
                Segments: { value: 25, max: 25 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 235 },
                SmallCircle: { value: 52 },
                StartCP: { value: 20 },
                MiddleCP: { value: 30 },
                Tilt: { value: -2 },
                Segments: { value: 33, max: 33 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 240 },
                SmallCircle: { value: 40 },
                StartCP: { value: 20 },
                MiddleCP: { value: 30 },
                Tilt: { value: 3 },
                Segments: { value: 41, max: 41 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 222 },
                SmallCircle: { value: 46 },
                StartCP: { value: 14 },
                MiddleCP: { value: 25 },
                Tilt: { value: 5 },
                Segments: { value: 49, max: 49 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 222 },
                SmallCircle: { value: 60 },
                StartCP: { value: 5 },
                MiddleCP: { value: 27 },
                Tilt: { value: 7 },
                Segments: { value: 57, max: 57 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 222 },
                SmallCircle: { value: 60 },
                StartCP: { value: 12 },
                MiddleCP: { value: 28 },
                Tilt: { value: 8 },
                Segments: { value: 65, max: 65 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 222 },
                SmallCircle: { value: 60 },
                StartCP: { value: 5 },
                MiddleCP: { value: 27 },
                Tilt: { value: 10 },
                Segments: { value: 73, max: 73 },
            },
        },
        Sa: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 4, max: 12 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 158 },
                SmallCircle: { value: 32 },
                StartCP: { value: 15 },
                MiddleCP: { value: 27 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 191 },
                SmallCircle: { value: 45 },
                StartCP: { value: 10 },
                MiddleCP: { value: 25 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 40 },
                StartCP: { value: 10 },
                MiddleCP: { value: 20 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 205 },
                SmallCircle: { value: 34 },
                StartCP: { value: 8 },
                MiddleCP: { value: 23 },
                Segments: { value: 29, max: 29 },
            },
            7.1: {
                Knots: { value: 7 },
                LargeCircle: { value: 205 },
                SmallCircle: { value: 57 },
                StartCP: { value: 9 },
                MiddleCP: { value: 18 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 43 },
                StartCP: { value: 6 },
                MiddleCP: { value: 18 },
                Segments: { value: 33, max: 33 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 235 },
                SmallCircle: { value: 53 },
                StartCP: { value: 5 },
                MiddleCP: { value: 19 },
                Segments: { value: 41, max: 41 },
            },
            12: {
                Knots: { value: 12 },
                LargeCircle: { value: 244 },
                SmallCircle: { value: 71 },
                StartCP: { value: 4 },
                MiddleCP: { value: 20 },
                Segments: { value: 49, max: 49 },
            },
        },
        Saa: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 4, max: 12 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 158 },
                SmallCircle: { value: 32 },
                StartCP: { value: 15 },
                MiddleCP: { value: 27 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 191 },
                SmallCircle: { value: 45 },
                StartCP: { value: 10 },
                MiddleCP: { value: 25 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 40 },
                StartCP: { value: 10 },
                MiddleCP: { value: 20 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 205 },
                SmallCircle: { value: 34 },
                StartCP: { value: 8 },
                MiddleCP: { value: 23 },
                Segments: { value: 29, max: 29 },
            },
            7.1: {
                Knots: { value: 7 },
                LargeCircle: { value: 205 },
                SmallCircle: { value: 57 },
                StartCP: { value: 9 },
                MiddleCP: { value: 18 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 43 },
                StartCP: { value: 6 },
                MiddleCP: { value: 18 },
                Segments: { value: 33, max: 33 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 235 },
                SmallCircle: { value: 53 },
                StartCP: { value: 5 },
                MiddleCP: { value: 19 },
                Segments: { value: 41, max: 41 },
            },
            12: {
                Knots: { value: 12 },
                LargeCircle: { value: 244 },
                SmallCircle: { value: 71 },
                StartCP: { value: 4 },
                MiddleCP: { value: 20 },
                Segments: { value: 49, max: 49 },
            },
        },
        S2: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 50, max: 200 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 90 },
                SmallCircle: { value: 17 },
                StartCP: { value: 32 },
                MiddleCP: { value: 17 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 85 },
                SmallCircle: { value: 35 },
                StartCP: { value: 33 },
                MiddleCP: { value: 19 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 91 },
                SmallCircle: { value: 39 },
                StartCP: { value: 32 },
                MiddleCP: { value: 20 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 99 },
                SmallCircle: { value: 67 },
                StartCP: { value: 22 },
                MiddleCP: { value: 51 },
                Segments: { value: 25, max: 25 },
            },
        },
        S3: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 6, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 39 },
                StartCP: { value: 39 },
                MiddleCP: { value: 23 },
                Segments: { value: 13, max: 13 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 39 },
                StartCP: { value: 32 },
                MiddleCP: { value: 23 },
                Segments: { value: 15, max: 15 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 54 },
                StartCP: { value: 30 },
                MiddleCP: { value: 23 },
                Segments: { value: 17, max: 17 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 54 },
                StartCP: { value: 22 },
                MiddleCP: { value: 23 },
                Segments: { value: 19, max: 19 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 298 },
                SmallCircle: { value: 74 },
                StartCP: { value: 22 },
                MiddleCP: { value: 23 },
                Segments: { value: 21, max: 21 },
            },
        },
        S4: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 100 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 300 },
                SmallCircle: { value: 39 },
                StartCP: { value: 19 },
                MiddleCP: { value: 6 },
                Segments: { value: 22, max: 22 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 300 },
                SmallCircle: { value: 65 },
                StartCP: { value: 25 },
                MiddleCP: { value: 8 },
                Segments: { value: 36, max: 36 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 300 },
                SmallCircle: { value: 67 },
                StartCP: { value: 18 },
                MiddleCP: { value: 14 },
                Segments: { value: 50, max: 50 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 300 },
                SmallCircle: { value: 47 },
                StartCP: { value: 17 },
                MiddleCP: { value: 15 },
                Segments: { value: 64, max: 64 },
            },
        },
        S5: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'ExtraCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'ExtraCP' },
                { name: 'Tilt' },
                { name: 'ExtraAngle' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 100, max: 500 },
                ExtraCircle: { min: -100, max: 400 },
                StartCP: { min: -100, max: 100 },
                MiddleCP: { min: 0, max: 150 },
                ExtraCP: { min: -200, max: 200 },
                Tilt: { min: -150, max: 150 },
                ExtraAngle: { min: -180, max: 180 },
                Segments: { min: 2, max: 100 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 213 },
                SmallCircle: { value: 325 },
                ExtraCircle: { value: 114 },
                StartCP: { value: 13 },
                MiddleCP: { value: 68 },
                ExtraCP: { value: 29 },
                Tilt: { value: 6 },
                ExtraAngle: { value: 129 },
                Segments: { value: 19, max: 19 },
            },
            3.1: {
                Knots: { value: 3 },
                LargeCircle: { value: 115 },
                SmallCircle: { value: 325 },
                ExtraCircle: { value: 114 },
                StartCP: { value: 13 },
                MiddleCP: { value: 68 },
                ExtraCP: { value: 29 },
                Tilt: { value: 6 },
                ExtraAngle: { value: 129 },
                Segments: { value: 19, max: 19 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 183 },
                SmallCircle: { value: 312 },
                ExtraCircle: { value: 108 },
                StartCP: { value: 14 },
                MiddleCP: { value: 44 },
                ExtraCP: { value: 92 },
                Tilt: { value: 14 },
                ExtraAngle: { value: 90 },
                Segments: { value: 25, max: 25 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 233 },
                SmallCircle: { value: 352 },
                ExtraCircle: { value: 107 },
                StartCP: { value: 18 },
                MiddleCP: { value: 122 },
                ExtraCP: { value: -47 },
                Tilt: { value: -135 },
                ExtraAngle: { value: 128 },
                Segments: { value: 31, max: 31 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 191 },
                SmallCircle: { value: 309 },
                ExtraCircle: { value: 93 },
                StartCP: { value: 18 },
                MiddleCP: { value: 27 },
                ExtraCP: { value: 78 },
                Tilt: { value: -64 },
                ExtraAngle: { value: 80 },
                Segments: { value: 37, max: 37 },
            },
            6.1: {
                Knots: { value: 6 },
                LargeCircle: { value: 201 },
                SmallCircle: { value: 351 },
                ExtraCircle: { value: 106 },
                StartCP: { value: 18 },
                MiddleCP: { value: 42 },
                ExtraCP: { value: 58 },
                Tilt: { value: 62 },
                ExtraAngle: { value: 108 },
                Segments: { value: 37, max: 37 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 213 },
                SmallCircle: { value: 348 },
                ExtraCircle: { value: 144 },
                StartCP: { value: 13 },
                MiddleCP: { value: 47 },
                ExtraCP: { value: 86 },
                Tilt: { value: 47 },
                ExtraAngle: { value: 138 },
                Segments: { value: 43, max: 43 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 258 },
                SmallCircle: { value: 347 },
                ExtraCircle: { value: 126 },
                StartCP: { value: 15 },
                MiddleCP: { value: 33 },
                ExtraCP: { value: 89 },
                Tilt: { value: 32 },
                ExtraAngle: { value: 116 },
                Segments: { value: 49, max: 49 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 228 },
                SmallCircle: { value: 351 },
                ExtraCircle: { value: 141 },
                StartCP: { value: 19 },
                MiddleCP: { value: 40 },
                ExtraCP: { value: 65 },
                Tilt: { value: 55 },
                ExtraAngle: { value: 152 },
                Segments: { value: 55, max: 55 },
            },
        },
        K: {
            sliders: [
                { name: 'Knots' },
                { name: 'LargeCircle' },
                { name: 'SmallCircle' },
                { name: 'StartCP' },
                { name: 'MiddleCP' },
                { name: 'Segments' },
            ],
            mat: {
                Knots: { min: 3, max: 9 },
                LargeCircle: { min: 100, max: 300 },
                SmallCircle: { min: 10, max: 200 },
                StartCP: { min: 0, max: 70 },
                MiddleCP: { min: 0, max: 80 },
                Segments: { min: 2, max: 17 },
            },
            3: {
                Knots: { value: 3 },
                LargeCircle: { value: 140 },
                SmallCircle: { value: 20 },
                StartCP: { value: 15 },
                MiddleCP: { value: 25 },
                Segments: { value: 13, max: 13 },
            },
            4: {
                Knots: { value: 4 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 50 },
                StartCP: { value: 10 },
                MiddleCP: { value: 26 },
                Segments: { value: 17, max: 17 },
            },
            5: {
                Knots: { value: 5 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 60 },
                StartCP: { value: 15 },
                MiddleCP: { value: 20 },
                Segments: { value: 21, max: 21 },
            },
            6: {
                Knots: { value: 6 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 60 },
                StartCP: { value: 15 },
                MiddleCP: { value: 20 },
                Segments: { value: 25, max: 25 },
            },
            7: {
                Knots: { value: 7 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 84 },
                StartCP: { value: 10 },
                MiddleCP: { value: 15 },
                Segments: { value: 29, max: 29 },
            },
            8: {
                Knots: { value: 8 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 84 },
                StartCP: { value: 10 },
                MiddleCP: { value: 15 },
                Segments: { value: 33, max: 33 },
            },
            9: {
                Knots: { value: 9 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 120 },
                StartCP: { value: 8 },
                MiddleCP: { value: 13 },
                Segments: { value: 37, max: 37 },
            },
            10: {
                Knots: { value: 10 },
                LargeCircle: { value: 200 },
                SmallCircle: { value: 120 },
                StartCP: { value: 8 },
                MiddleCP: { value: 13 },
                Segments: { value: 41, max: 41 },
            },
        },
    };
}
