// V1 Presets
export const v1Presets = {
    sliders: [
        { name: 'Knots' },
        { name: 'LargeCircle' },
        { name: 'SmallCircle' },
        { name: 'StartCP' },
        { name: 'MiddleCP' },
        { name: 'Segments' },
    ],
    mat: {
        Knots: { min: 3, max: 9 },
        LargeCircle: { min: 50, max: 300 },
        SmallCircle: { min: 1, max: 200 },
        StartCP: { min: 0, max: 70 },
        MiddleCP: { min: 0, max: 80 },
        Segments: { min: 2, max: 17 },
    },
    3: {
        Knots: { value: 3 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 9 },
        StartCP: { value: 20 },
        MiddleCP: { value: 49 },
        Segments: { value: 13, max: 13 },
    },
    4: {
        Knots: { value: 4 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 21 },
        StartCP: { value: 19 },
        MiddleCP: { value: 32 },
        Segments: { value: 17, max: 17 },
    },
    5: {
        Knots: { value: 5 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 32 },
        StartCP: { value: 16 },
        MiddleCP: { value: 27 },
        Segments: { value: 21, max: 21 },
    },
    6: {
        Knots: { value: 6 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 47 },
        StartCP: { value: 14 },
        MiddleCP: { value: 21 },
        Segments: { value: 25, max: 25 },
    },
    7: {
        Knots: { value: 7 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 39 },
        StartCP: { value: 13 },
        MiddleCP: { value: 18 },
        Segments: { value: 29, max: 29 },
    },
    8: {
        Knots: { value: 8 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 49 },
        StartCP: { value: 11 },
        MiddleCP: { value: 15 },
        Segments: { value: 33, max: 33 },
    },
    9: {
        Knots: { value: 9 },
        LargeCircle: { value: 298 },
        SmallCircle: { value: 55 },
        StartCP: { value: 10 },
        MiddleCP: { value: 17 },
        Segments: { value: 37, max: 37 },
    },
};
