// V2 Presets
export const v2Presets = {
    sliders: [
        { name: 'Knots'       },
        { name: 'ExtraCircle' },
        { name: 'LargeCircle' },
        { name: 'SmallCircle' },
        { name: 'StartCP'     },
        { name: 'MiddleCP'    },
        { name: 'CP1'         },
        { name: 'CP2'         },
        { name: 'Tilt'        },
        { name: 'Segments'    },
    ],
    mat: {
        Knots:       { min: 3,    max: 9    },
        ExtraCircle: { min: 50,   max: 500  },
        LargeCircle: { min: 50,   max: 400  },
        SmallCircle: { min: 1,    max: 200  },
        ExtraCP:     { min: 0,    max: 70   },
        StartCP:     { min: 0,    max: 70   },
        MiddleCP:    { min: 0,    max: 80   },
        ExtraAngle:  { min: -180, max: 180  },
        CP1:         { min: 0,    max: 80   },
        CP2:         { min: 0,    max: 80   },
        Tilt:        { min: -180, max: 180  },
        Segments:    { min: 2,    max: 17   },
    },
    3: {
        Knots:       { value: 3           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 60          },
        ExtraCP:     { value: 46          },
        StartCP:     { value: 45          },
        MiddleCP:    { value: 19          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 32          },
        CP2:         { value: 39          },
        Tilt:        { value: -23         },
        Segments:    { value: 19, max: 19 },
    },
    4: {
        Knots:       { value: 4           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 88          },
        ExtraCP:     { value: 42          },
        StartCP:     { value: 37          },
        MiddleCP:    { value: 19          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 22          },
        CP2:         { value: 27          },
        Tilt:        { value: -29         },
        Segments:    { value: 25, max: 25 },
    },
    '4.1': {
        Knots:       { value: 4           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 88          },
        ExtraCP:     { value: 25          },
        StartCP:     { value: 25          },
        MiddleCP:    { value: 35          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 46          },
        CP2:         { value: 43          },
        Tilt:        { value: 158         },
        Segments:    { value: 25, max: 25 },
    },
    5: {
        Knots:       { value: 5           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 122         },
        ExtraCP:     { value: 37          },
        StartCP:     { value: 37          },
        MiddleCP:    { value: 16          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 26          },
        CP2:         { value: 29          },
        Tilt:        { value: -33         },
        Segments:    { value: 31, max: 31 },
    },
    6: {
        Knots:       { value: 6           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 124         },
        ExtraCP:     { value: 37          },
        StartCP:     { value: 29          },
        MiddleCP:    { value: 12          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 24          },
        CP2:         { value: 30          },
        Tilt:        { value: -21         },
        Segments:    { value: 37, max: 37 },
    },
    7: {
        Knots:       { value: 7           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 162         },
        ExtraCP:     { value: 37          },
        StartCP:     { value: 29          },
        MiddleCP:    { value: 12          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 24          },
        CP2:         { value: 30          },
        Tilt:        { value: -21         },
        Segments:    { value: 43, max: 43 },
    },
    8: {
        Knots:       { value: 8           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 167         },
        ExtraCP:     { value: 37          },
        StartCP:     { value: 22          },
        MiddleCP:    { value: 10          },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 20          },
        CP2:         { value: 29          },
        Tilt:        { value: -20         },
        Segments:    { value: 49, max: 49 },
    },
    9: {
        Knots:       { value: 9           },
        ExtraCircle: { value: 336         },
        LargeCircle: { value: 291         },
        SmallCircle: { value: 169         },
        ExtraCP:     { value: 37          },
        StartCP:     { value: 22          },
        MiddleCP:    { value: 8           },
        ExtraAngle:  { value: 0           },
        CP1:         { value: 20          },
        CP2:         { value: 29          },
        Tilt:        { value: -20         },
        Segments:    { value: 55, max: 55 },
    },
};
