// V4 Presets
export const v4Presets = {
    sliders: [
        { name: 'Knots'       },
        { name: 'ExtraCircle' },
        { name: 'LargeCircle' },
        { name: 'SmallCircle' },
        { name: 'StartCP'     },
        { name: 'MiddleCP'    },
        { name: 'CP1'         },
        { name: 'CP2'         },
        { name: 'Tilt'        },
        { name: 'Segments'    },
    ],
    mat: {
        Knots:       { min: 4,    max: 14   },
        ExtraCircle: { min: 50,   max: 500  },
        LargeCircle: { min: 50,   max: 400  },
        SmallCircle: { min: 1,    max: 200  },
        StartCP:     { min: 0,    max: 70   },
        MiddleCP:    { min: 0,    max: 80   },
        CP1:         { min: 0,    max: 580  },
        CP2:         { min: 0,    max: 580  },
        Tilt:        { min: -180, max: 180 },
        Segments:    { min: 2,    max: 17   },
    },
    4: {
        Knots:       { value: 4           },
        ExtraCircle: { value: 80          },
        LargeCircle: { value: 300         },
        SmallCircle: { value: 25          },
        StartCP:     { value: 14          },
        MiddleCP:    { value: 50          },
        CP1:         { value: 427         },
        CP2:         { value: 42          },
        Tilt:        { value: 160         },
        Segments:    { value: 17, max: 17 },
    },
    5: {
        Knots:       { value: 5           },
        ExtraCircle: { value: 120         },
        LargeCircle: { value: 351         },
        SmallCircle: { value: 45          },
        StartCP:     { value: 36          },
        MiddleCP:    { value: 30          },
        CP1:         { value: 52          },
        CP2:         { value: 62          },
        Tilt:        { value: 45          },
        Segments:    { value: 21, max: 21 },
    },
    7: {
        Knots:       { value: 7           },
        ExtraCircle: { value: 160         },
        LargeCircle: { value: 351         },
        SmallCircle: { value: 75          },
        StartCP:     { value: 32          },
        MiddleCP:    { value: 24          },
        CP1:         { value: 52          },
        CP2:         { value: 62          },
        Tilt:        { value: 45          },
        Segments:    { value: 29, max: 29 },
    },
    8: {
        Knots:       { value: 8           },
        ExtraCircle: { value: 130         },
        LargeCircle: { value: 300         },
        SmallCircle: { value: 80          },
        StartCP:     { value: 10          },
        MiddleCP:    { value: 30          },
        CP1:         { value: 230         },
        CP2:         { value: 54          },
        Tilt:        { value: 166         },
        Segments:    { value: 33, max: 33 },
    },
    9: {
        Knots:       { value: 9           },
        ExtraCircle: { value: 200         },
        LargeCircle: { value: 351         },
        SmallCircle: { value: 115         },
        StartCP:     { value: 28          },
        MiddleCP:    { value: 20          },
        CP1:         { value: 52          },
        CP2:         { value: 42          },
        Tilt:        { value: 45          },
        Segments:    { value: 37, max: 37 },
    },
};
