// V5 Presets
export const v5Presets = {
    sliders: [
        { name: 'Knots'       },
        { name: 'ExtraCircle' },
        { name: 'LargeCircle' },
        { name: 'SmallCircle' },
        { name: 'StartCP'     },
        { name: 'MiddleCP'    },
        { name: 'CP1'         },
        { name: 'CP2'         },
        { name: 'Tilt'        },
        { name: 'Segments'    },
    ],
    mat: {
        Knots:       { min: 3,    max: 14   },
        ExtraCircle: { min: 50,   max: 500  },
        LargeCircle: { min: 50,   max: 400  },
        SmallCircle: { min: 1,    max: 200  },
        StartCP:     { min: 0,    max: 70   },
        MiddleCP:    { min: 0,    max: 80   },
        CP1:         { min: 0,    max: 580  },
        CP2:         { min: 0,    max: 580  },
        Tilt:        { min: -180, max: 180  },
        Segments:    { min: 2,    max: 17   },
    },
    4: {
        Knots:       { value: 4            },
        ExtraCircle: { value: 168          },
        LargeCircle: { value: 317          },
        SmallCircle: { value: 18           },
        StartCP:     { value: 33           },
        MiddleCP:    { value: 44           },
        CP1:         { value: 501          },
        CP2:         { value: 197          },
        Tilt:        { value: 172          },
        Segments:    { value: 17, max: 17  },
    },
    6: {
        Knots:       { value: 6            },
        ExtraCircle: { value: 136          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 42           },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 259          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 25, max: 25  },
    },
    7: {
        Knots:       { value: 7            },
        ExtraCircle: { value: 136          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 42           },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 225          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 29, max: 29  },
    },
    8: {
        Knots:       { value: 8            },
        ExtraCircle: { value: 162          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 63           },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 204          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 33, max: 33  },
    },
    9: {
        Knots:       { value: 9            },
        ExtraCircle: { value: 162          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 63           },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 167          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 37, max: 37  },
    },
    11: {
        Knots:       { value: 11           },
        ExtraCircle: { value: 184          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 97           },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 128          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 45, max: 45  },
    },
    12: {
        Knots:       { value: 12           },
        ExtraCircle: { value: 184          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 105          },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 116          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 49, max: 49  },
    },
    13: {
        Knots:       { value: 13           },
        ExtraCircle: { value: 184          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 105          },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 95           },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 53, max: 53  },
    },
    14: {
        Knots:       { value: 14           },
        ExtraCircle: { value: 184          },
        LargeCircle: { value: 316          },
        SmallCircle: { value: 105          },
        StartCP:     { value: 32           },
        MiddleCP:    { value: 30           },
        CP1:         { value: 110          },
        CP2:         { value: 54           },
        Tilt:        { value: 166          },
        Segments:    { value: 57, max: 57  },
    },
};
